@echo off
echo Initializing git...
git init
echo Creating README.md...
echo # ApnaStore > README.md
echo Adding README.md...
git add README.md
echo Committing...
git commit -m "first commit"
echo Renaming branch...
git branch -M main
echo Adding remote...
git remote add origin https://github.com/abhi-7320/ApnaStore.git
echo Pushing...
git push -u origin main
echo Done.
